### ISSUE TITLE
sistem informasi manajemen akademik di ra al-ikhlas cihaurbeuti berbasis website

### ISSUE THREAD

**Issue by Neng-01** [hajirodeon/SISFOKOL#1]
buatkan sistem manajemen akademik di ra al-ikhlas cihaurbeuti berbasis website , dengan fitur fitur terbaru, admin,login. username.password input data siswa . absensi , informasi lewat notifikasi dan lain lain

**Comment by hajirodeon** [comment]
silahkan bisa dicoba dulu ya, sisfokol-nya.

untuk kebutuhan custom berbayar, silahkan bisa inbox via email ataupun via wa.
